---
kind: "operation"
client: "rug-cli 0.22.0"
generator:
  name: "NewRugArchiveProject"
  group: "atomist-rugs"
  artifact: "rug-archive"
  version: "0.9.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-archive.git"
    branch: "504e54d3fff7463db6b1f09f6fcb94e91357e4f3"
    sha: "504e54d"
  parameters:
    - "group_id": "eddumelendez"
    - "version": "0.1.0"
    - "description": "Rugs for Spring Boot projects"
    - "project_name": "spring-boot-rugs"

